name: Backend-Deployment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: self-hosted
    container: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install --no-install-recommends -y binutils libproj-dev gdal-bin python-gdal
          python -m pip install --upgrade pip
          pip install -r social/requirements.txt
      - name: Run Django Tests
        run: |
          python social/manage.py test
  
  deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    needs: build
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: $||secrets.DEV_BACKEND_SERVER_IP||
          username: $||secrets.DEV_BACKEND_SERVER_USERNAME||
          key: $||secrets.DEV_BACKEND_SSHKEY||
          script: >
            cd $||secrets.DEV_BACKEND_PROJECT_PATH||
            && git pull 
            && chmod 655 mng-api.sh 
            && chmod 655 ./social/manage.py 
            && ./mng-api.sh up